version: "3"
services:
  sshd:
    build:
      context: .
      dockerfile: Dockerfile
    image: ztj1993/sshd:latest
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 22/tcp
    ports:
      - 22/tcp
